version: '3.8'
services:
  apache:
    build:
      dockerfile: ./docker/php/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=contact
      - MYSQL_USER=exo_contact
      - MYSQL_PASSWORD=jo1234
    ports: 
      - 80:80
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html 
  mysql: 
    image: mysql
    ports: 
      - 3307:3306 
    volumes:
      - type: volume
        source: contact
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=contact
      - MYSQL_USER=exo_contact
      - MYSQL_PASSWORD=jo1234
volumes:
  contact: 
    